variables:
  PRIMARY_BRANCH: "main"
  DEPLOY_REPO: 'git@gitlab.clarium.tech:clarium-org-apps/sso/sso-apps-deploy.git'
  TARGET_BRANCH: "stage-dev"
  MODULE: "sso-ui"
  SOURCE_DIRECTORY: "./dist/oauth2-angular-app/browser"

include:
  - project: "devops/gitlab_yamls"
    ref: "Framework_template"
    file: "angular.gitlab-ci.yml"
